// scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ICON_NAMES } from './icon-names.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// lucide-static is a devDep of @klavity/core; pnpm installs it in packages/core/node_modules
const lucideDir = join(root, 'packages', 'core', 'node_modules', 'lucide-static', 'icons');

// Pull the inner markup (everything between <svg ...> and </svg>) verbatim from lucide-static.
function inner(name) {
  const svg = readFileSync(join(lucideDir, `${name}.svg`), 'utf8');
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error(`Cannot parse lucide icon: ${name}`);
  return m[1].replace(/\s+/g, ' ').trim();
}

const entries = ICON_NAMES.map((n) => [n, inner(n)]);
const map = Object.fromEntries(entries);

const banner = '// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit. Run `pnpm gen:icons`.\n';
writeFileSync(
  join(root, 'packages', 'core', 'src', 'icons.generated.ts'),
  banner + 'export const ICONS = ' + JSON.stringify(map, null, 2) + ' as const;\n',
);
writeFileSync(
  join(root, 'site', 'icons.generated.js'),
  banner + 'window.KLAV_ICONS = ' + JSON.stringify(map, null, 2) + ';\n',
);
console.log(`Generated ${ICON_NAMES.length} icons.`);
