// scripts/gen-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { ICON_NAMES } from './icon-names.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
// lucide-static is a devDep of @klavity/core; pnpm installs it in packages/core/node_modules
const lucideDir = join(root, 'packages', 'core', 'node_modules', 'lucide-static', 'icons');

// Pull the inner markup (everything between <svg ...> and </svg>) verbatim from lucide-static.
function inner(name) {
  const svg = readFileSync(join(lucideDir, `${name}.svg`), 'utf8');
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!m) throw new Error(`Cannot parse lucide icon: ${name}`);
  return m[1].replace(/\s+/g, ' ').trim();
}

const entries = ICON_NAMES.map((n) => [n, inner(n)]);
const map = Object.fromEntries(entries);

const banner = '// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit. Run `pnpm gen:icons`.\n';
writeFileSync(
  join(root, 'packages', 'core', 'src', 'icons.generated.ts'),
  banner + 'export const ICONS = ' + JSON.stringify(map, null, 2) + ' as const;\n',
);
writeFileSync(
  join(root, 'site', 'icons.generated.js'),
  banner + 'window.KLAV_ICONS = ' + JSON.stringify(map, null, 2) + ';\n',
);

// Self-contained helper for prototype/public app pages (they do not load site/kit.js).
// Exposes window.kicon(name, opts) mirroring @klavity/core icon().
const kicon = [
  banner,
  'window.KLAV_ICONS = ' + JSON.stringify(map, null, 2) + ';',
  '(function(){',
  '  // Baseline-align inline icons app-wide: one .icon rule covers both hardcoded',
  '  // class="icon" SVGs (e.g. nav) and kicon() output. Injected once on load so',
  '  // every prototype page that loads this file is fixed without per-page CSS.',
  '  try {',
  '    if (typeof document !== "undefined" && !document.getElementById("klav-icon-align")) {',
  '      var _st = document.createElement("style");',
  '      _st.id = "klav-icon-align";',
  '      _st.textContent = ".icon{vertical-align:-0.125em}";',
  '      (document.head || document.documentElement).appendChild(_st);',
  '    }',
  '  } catch (e) {}',
  '  function esc(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}',
  '  window.kicon = function(name, opts){',
  '    opts = opts || {};',
  '    var body = (window.KLAV_ICONS || {})[name];',
  '    if (!body) throw new Error("Unknown icon: " + name);',
  '    var size = opts.size ?? 18;',
  '    var cls = opts.class ? "icon " + opts.class : "icon";',
  '    var a11y = opts.label ? "role=\\"img\\"" : "aria-hidden=\\"true\\"";',
  '    var title = opts.label ? "<title>" + esc(opts.label) + "</title>" : "";',
  '    return "<svg xmlns=\\"http://www.w3.org/2000/svg\\" class=\\"" + cls + "\\" width=\\"" + size + "\\" height=\\"" + size +',
  '      "\\" viewBox=\\"0 0 24 24\\" fill=\\"none\\" stroke=\\"currentColor\\" stroke-width=\\"2\\" stroke-linecap=\\"round\\" stroke-linejoin=\\"round\\" style=\\"vertical-align:-0.125em\\" " +',
  '      a11y + ">" + title + body + "</svg>";',
  '  };',
  '})();',
  '',
].join('\n');
writeFileSync(join(root, 'prototype', 'public', 'icons.generated.js'), kicon);
console.log(`Generated ${ICON_NAMES.length} icons.`);
